services:
  web:
    build:
      context: .
    image: teams
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    restart: always
  migrate:
    image: teams
    depends_on:
      - db
    volumes:
      - .:/app
    env_file: .env
    command: python manage.py migrate
    restart: on-failure
  db:
    image: postgres
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.50'
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: 'admin123'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'